name: "[ansible-playbook] Deploy Static Site Generated Website"

on:
  workflow_call:
    inputs:
      invoking_github_object:
        required: false
        type: string
      fqdn:                   # fqdn of target deployment website
        required: false
        type: string

jobs: 
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.invoking_github_object }}"
  ansible-playbook:
    runs-on: self-hosted
    steps:
      - run: run-ansible-playbook.sh playbooks/ping.yaml
      #- run: run-ansible-playbook.sh playbooks/deploy-ssg-website.yaml -e input_website_fqdn=${{ inputs.fqdn }}
