name: "[ansible-playbook] Deploy Static Site Generated Website"

on:
  workflow_call:
    inputs:
      fqdn:                   # fqdn of target deployment website
        required: false
        type: string

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.fqdn }}
  ansible-playbook:
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    steps:
      - run: run-ansible-playbook.sh playbooks/ping.yaml
      #- run: run-ansible-playbook.sh playbooks/deploy-ssg-website.yaml -e input_website_fqdn=${{ inputs.fqdn }}
