name: hello-world

on:
  workflow_call:
    inputs:
      param-one:                # name of build artifact to transfer between jobs/workflows
        required: true
        type: string

jobs: 

  echo:
    runs-on: self-hosted
    steps:
      - run: hostname
      - run: uname -a
